[2023-12-21 12:49:50,393: INFO: main: welcome to our custom log]
[2023-12-27 13:12:23,301: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:14:05,718: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:19:55,785: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:24:08,120: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:25:04,000: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:27:01,313: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:27:58,870: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:27:59,539: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:27:59,919: INFO: common: yaml file:config\config.yaml loaded successfully]
[2023-12-27 13:29:30,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 13:29:30,293: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 13:30:58,500: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 13:30:58,500: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 13:32:02,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 13:32:02,560: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 13:34:10,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 13:34:10,060: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 13:34:34,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 13:34:34,959: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 13:36:53,843: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 13:36:53,851: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 13:37:07,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 13:37:07,091: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 13:37:07,096: INFO: common: created directory at: artifacts]
[2023-12-27 13:37:07,098: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-27 13:37:07,099: INFO: 2400936337: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 13:38:40,321: INFO: 2400936337: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 17:51:10,754: INFO: main: .....stage Data ingestion stage started ....]
[2023-12-27 17:51:10,755: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 17:51:10,755: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 17:51:10,755: INFO: common: created directory at: artifacts]
[2023-12-27 17:51:10,755: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-27 17:51:10,759: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 17:53:23,435: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 17:53:25,232: INFO: main: ..... stage Data ingestion stage completed .....]
[2023-12-27 18:04:11,824: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 18:04:11,833: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 18:04:11,834: INFO: common: created directory at: artifacts]
[2023-12-27 18:04:11,834: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-27 18:04:11,838: INFO: 3202872001: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 18:08:04,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-27 18:08:04,562: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-27 18:08:04,562: INFO: common: created directory at: artifacts]
[2023-12-27 18:08:04,562: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-27 18:08:04,566: INFO: 4234615999: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-27 18:11:00,457: INFO: 4234615999: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-29 11:18:51,041: INFO: main: .....stage Data ingestion stage started ....]
[2023-12-29 11:18:51,042: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 11:18:51,042: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 11:18:51,043: INFO: common: created directory at: artifacts]
[2023-12-29 11:18:51,043: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-29 11:18:51,043: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-29 11:21:15,021: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-29 11:21:16,040: INFO: main: ..... stage Data ingestion stage completed .....]
[2023-12-29 17:38:31,144: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:38:31,150: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:38:31,150: INFO: common: created directory at: artifacts]
[2023-12-29 17:38:31,150: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:41:30,880: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 17:45:44,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:45:44,189: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:45:44,195: INFO: common: created directory at: artifacts]
[2023-12-29 17:45:44,197: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:45:44,695: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 17:49:43,589: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:49:43,599: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:49:43,599: INFO: common: created directory at: artifacts]
[2023-12-29 17:49:43,607: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:49:44,117: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 17:50:11,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:50:11,664: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:50:11,671: INFO: common: created directory at: artifacts]
[2023-12-29 17:50:11,671: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:50:12,180: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 17:50:15,515: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:50:15,519: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:50:15,524: INFO: common: created directory at: artifacts]
[2023-12-29 17:50:15,524: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:50:16,035: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 17:50:34,641: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:50:34,647: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:50:34,652: INFO: common: created directory at: artifacts]
[2023-12-29 17:50:34,656: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:50:35,192: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 17:51:51,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:51:51,027: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:51:51,031: INFO: common: created directory at: artifacts]
[2023-12-29 17:51:51,035: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:51:51,537: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 17:51:57,469: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 17:51:57,478: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 17:51:57,478: INFO: common: created directory at: artifacts]
[2023-12-29 17:51:57,481: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 17:51:57,991: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 18:09:06,306: INFO: main: .....stage Data ingestion stage started ....]
[2023-12-29 18:09:06,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 18:09:06,314: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 18:09:06,314: INFO: common: created directory at: artifacts]
[2023-12-29 18:09:06,314: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-29 18:09:06,314: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-29 18:11:55,989: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-29 18:11:57,606: INFO: main: ..... stage Data ingestion stage completed .....]
[2023-12-29 18:11:57,608: INFO: main: .....stage prepare base model started ....]
[2023-12-29 18:11:57,612: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-29 18:11:57,615: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-29 18:11:57,616: INFO: common: created directory at: artifacts]
[2023-12-29 18:11:57,616: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-29 18:11:58,687: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-29 18:11:59,131: INFO: main: ..... stage prepare base model completed .....]
[2024-01-11 13:55:24,246: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 13:55:24,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 13:55:24,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 13:55:24,281: INFO: common: created directory at: artifacts]
[2024-01-11 13:55:24,289: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 13:55:24,297: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 13:55:25,742: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 13:55:26,252: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-11 13:55:26,252: INFO: main: .....stage prepare base model started ....]
[2024-01-11 13:55:26,253: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 13:55:26,254: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 13:55:26,254: INFO: common: created directory at: artifacts]
[2024-01-11 13:55:26,255: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-11 13:55:26,706: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-11 13:55:26,918: INFO: main: ..... stage prepare base model completed .....]
[2024-01-11 13:57:46,232: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 13:57:46,232: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 13:57:46,232: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 13:57:46,232: INFO: common: created directory at: artifacts]
[2024-01-11 13:57:46,232: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 13:57:46,232: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 13:57:47,933: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 13:57:48,350: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-11 13:57:48,350: INFO: main: .....stage prepare base model started ....]
[2024-01-11 13:57:48,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 13:57:48,350: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 13:57:48,350: INFO: common: created directory at: artifacts]
[2024-01-11 13:57:48,350: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-11 13:57:48,690: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-11 13:57:48,975: INFO: main: ..... stage prepare base model completed .....]
[2024-01-11 13:59:01,639: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 13:59:01,639: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 13:59:01,639: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 13:59:01,654: INFO: common: created directory at: artifacts]
[2024-01-11 13:59:01,654: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 13:59:01,654: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 13:59:03,317: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 13:59:03,317: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 30, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file,'r') as zip_ref:
  File "C:\Users\rvaib\.conda\envs\envk\lib\zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-11 14:01:12,428: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 14:01:12,430: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:01:12,430: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:01:12,430: INFO: common: created directory at: artifacts]
[2024-01-11 14:01:12,430: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:01:12,430: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:01:13,800: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:01:13,800: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 30, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file,'r') as zip_ref:
  File "C:\Users\rvaib\.conda\envs\envk\lib\zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-11 14:01:50,322: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:01:50,325: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:01:50,327: INFO: common: created directory at: artifacts]
[2024-01-11 14:01:50,329: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:01:50,330: INFO: 4234615999: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:01:51,592: INFO: 4234615999: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:03:59,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:03:59,807: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:03:59,808: INFO: common: created directory at: artifacts]
[2024-01-11 14:03:59,809: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:03:59,810: INFO: 4234615999: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:04:01,552: INFO: 4234615999: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:04:26,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:04:26,832: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:04:26,834: INFO: common: created directory at: artifacts]
[2024-01-11 14:04:26,835: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:04:26,835: INFO: 4234615999: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:04:28,078: INFO: 4234615999: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:07:35,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:07:35,661: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:07:35,663: INFO: common: created directory at: artifacts]
[2024-01-11 14:07:35,666: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:07:35,666: INFO: 3810163852: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:07:36,976: INFO: 3810163852: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:09:08,081: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:09:08,090: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:09:08,092: INFO: common: created directory at: artifacts]
[2024-01-11 14:09:08,093: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:09:08,094: INFO: 3810163852: Downloading data from https://drive.google.com/file/d/1pxnILlW41Xh-kRhITozRHgnjXZH8jMrL/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:09:10,296: INFO: 3810163852: Downloaded data from https://drive.google.com/file/d/1pxnILlW41Xh-kRhITozRHgnjXZH8jMrL/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:09:35,038: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:09:35,041: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:09:35,041: INFO: common: created directory at: artifacts]
[2024-01-11 14:09:35,041: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:09:35,041: INFO: 3810163852: Downloading data from https://drive.google.com/file/d/1pxnILlW41Xh-kRhITozRHgnjXZH8jMrL/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:15:37,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:15:37,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:15:37,298: INFO: common: created directory at: artifacts]
[2024-01-11 14:15:37,300: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:15:37,301: INFO: 1617516281: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:15:38,629: INFO: 1617516281: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:24:55,203: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:24:55,205: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:24:55,206: INFO: common: created directory at: artifacts]
[2024-01-11 14:24:55,207: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:24:55,207: INFO: 706845714: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:24:56,201: INFO: 706845714: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:27:35,079: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 14:27:35,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:27:35,079: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:27:35,079: INFO: common: created directory at: artifacts]
[2024-01-11 14:27:35,079: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:27:35,079: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:27:36,335: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:27:36,335: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 30, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file,'r') as zip_ref:
  File "C:\Users\rvaib\.conda\envs\envk\lib\zipfile.py", line 1234, in __init__
    self._RealGetContents()
  File "C:\Users\rvaib\.conda\envs\envk\lib\zipfile.py", line 1301, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-01-11 14:29:44,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:29:44,685: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:29:44,687: INFO: common: created directory at: artifacts]
[2024-01-11 14:29:44,689: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:29:44,690: INFO: 376682446: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:29:45,996: INFO: 376682446: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:30:02,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:30:02,730: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:30:02,730: INFO: common: created directory at: artifacts]
[2024-01-11 14:30:02,737: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:30:02,739: INFO: 3403167183: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:30:04,392: INFO: 3403167183: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:31:43,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:31:43,263: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:31:43,263: INFO: common: created directory at: artifacts]
[2024-01-11 14:31:43,266: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:31:43,267: INFO: 1705949239: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:31:43,755: INFO: 1705949239: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:31:53,541: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:31:53,543: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:31:53,544: INFO: common: created directory at: artifacts]
[2024-01-11 14:31:53,545: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:31:53,546: INFO: 1705949239: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:31:53,995: INFO: 1705949239: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:33:06,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:33:06,856: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:33:06,857: INFO: common: created directory at: artifacts]
[2024-01-11 14:33:06,857: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:33:06,858: INFO: 1705949239: Downloading data from https://drive.google.com/file/d/1ZWpZ_KxsMVZ0SnqYTjUKr0MWHSf2ObJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:33:07,322: INFO: 1705949239: Downloaded data from https://drive.google.com/file/d/1ZWpZ_KxsMVZ0SnqYTjUKr0MWHSf2ObJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:37:44,997: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 14:37:45,004: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:37:45,004: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:37:45,004: INFO: common: created directory at: artifacts]
[2024-01-11 14:37:45,013: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:37:45,013: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1ZWpZ_KxsMVZ0SnqYTjUKr0MWHSf2ObJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:37:46,256: ERROR: main: 'NoneType' object has no attribute 'groups']
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 24, in download_file
    raise e
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\rvaib\.conda\envs\envk\lib\site-packages\gdown\download.py", line 259, in download
    filename_from_url = m.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
[2024-01-11 14:38:14,451: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:38:14,454: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:38:14,455: INFO: common: created directory at: artifacts]
[2024-01-11 14:38:14,456: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:38:14,457: INFO: 1705949239: Downloading data from https://drive.google.com/file/d/1ZWpZ_KxsMVZ0SnqYTjUKr0MWHSf2ObJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:38:14,929: INFO: 1705949239: Downloaded data from https://drive.google.com/file/d/1ZWpZ_KxsMVZ0SnqYTjUKr0MWHSf2ObJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:40:13,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:40:13,471: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:40:13,473: INFO: common: created directory at: artifacts]
[2024-01-11 14:40:13,473: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:40:13,475: INFO: 1705949239: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:40:13,932: INFO: 1705949239: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:40:41,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:40:41,721: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:40:41,722: INFO: common: created directory at: artifacts]
[2024-01-11 14:40:41,723: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:40:41,723: INFO: 2052301525: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:40:42,184: INFO: 2052301525: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:43:11,439: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:43:11,441: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:43:11,442: INFO: common: created directory at: artifacts]
[2024-01-11 14:43:11,442: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:43:11,443: INFO: 2052301525: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:43:12,211: INFO: 2052301525: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:47:55,677: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:47:55,679: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:47:55,680: INFO: common: created directory at: artifacts]
[2024-01-11 14:47:55,681: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:47:55,681: INFO: 525569051: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:47:56,327: INFO: 525569051: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:49:36,469: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:49:36,475: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:49:36,478: INFO: common: created directory at: artifacts]
[2024-01-11 14:49:36,479: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:50:46,080: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 14:50:46,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:50:46,080: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:50:46,080: INFO: common: created directory at: artifacts]
[2024-01-11 14:50:46,080: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:50:46,080: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:50:47,654: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:50:47,654: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 30, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file,'r') as zip_ref:
  File "C:\Users\rvaib\.conda\envs\envk\lib\zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-11 14:52:04,194: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-11 14:52:04,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:52:04,196: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:52:04,197: INFO: common: created directory at: artifacts]
[2024-01-11 14:52:04,197: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:52:04,197: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:52:06,101: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:52:06,512: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-11 14:52:06,513: INFO: main: .....stage prepare base model started ....]
[2024-01-11 14:52:06,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:52:06,535: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:52:06,550: INFO: common: created directory at: artifacts]
[2024-01-11 14:52:06,555: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-11 14:52:06,867: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-11 14:52:07,037: INFO: main: ..... stage prepare base model completed .....]
[2024-01-11 14:52:44,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:52:44,477: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:52:44,478: INFO: common: created directory at: artifacts]
[2024-01-11 14:52:44,479: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:52:44,479: INFO: 912916727: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:52:46,131: INFO: 912916727: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:53:16,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:53:16,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:53:16,170: INFO: common: created directory at: artifacts]
[2024-01-11 14:53:16,171: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:53:16,172: INFO: 912916727: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:53:17,898: INFO: 912916727: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:53:37,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:53:37,269: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:53:37,272: INFO: common: created directory at: artifacts]
[2024-01-11 14:53:37,274: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:53:37,276: INFO: 912916727: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:53:38,922: INFO: 912916727: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:54:49,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:54:49,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:54:49,954: INFO: common: created directory at: artifacts]
[2024-01-11 14:54:49,955: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:54:49,956: INFO: 3396119162: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:54:50,573: INFO: 3396119162: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:57:20,653: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 14:57:20,655: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 14:57:20,657: INFO: common: created directory at: artifacts]
[2024-01-11 14:57:20,658: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 14:57:20,658: INFO: 1727935137: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 14:57:22,327: INFO: 1727935137: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:04:15,379: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:04:15,380: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:04:15,381: INFO: common: created directory at: artifacts]
[2024-01-11 15:04:15,382: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:04:15,382: INFO: 2157536776: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:04:46,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:04:46,446: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:04:46,448: INFO: common: created directory at: artifacts]
[2024-01-11 15:04:46,450: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:04:46,451: INFO: 447182297: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:05:03,859: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:05:03,864: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:05:03,866: INFO: common: created directory at: artifacts]
[2024-01-11 15:05:03,867: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:05:03,869: INFO: 1796547561: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:05:05,487: INFO: 1796547561: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:06:20,085: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:06:20,089: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:06:20,090: INFO: common: created directory at: artifacts]
[2024-01-11 15:06:20,092: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:06:20,093: INFO: 1727935137: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:06:21,597: INFO: 1727935137: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:15:31,623: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:15:31,626: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:15:31,627: INFO: common: created directory at: artifacts]
[2024-01-11 15:15:31,627: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:15:31,628: INFO: 456661562: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:15:33,474: INFO: 456661562: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:18:56,043: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:18:56,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:18:56,050: INFO: common: created directory at: artifacts]
[2024-01-11 15:18:56,052: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:18:56,054: INFO: 456661562: downloading dataset fromhttps://drive.google.com/file/d/<10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE>&confirm=t/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:18:56,733: INFO: 456661562: downloaded dataset fromhttps://drive.google.com/file/d/<10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE>&confirm=t/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:20:27,035: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:20:27,037: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:20:27,038: INFO: common: created directory at: artifacts]
[2024-01-11 15:20:27,039: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:20:27,040: INFO: 456661562: downloading dataset fromhttps://drive.google.com/file/d/<10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE>&confirm=t/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:20:27,604: INFO: 456661562: downloaded dataset fromhttps://drive.google.com/file/d/<10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE>&confirm=t/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:20:38,317: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:20:38,320: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:20:38,321: INFO: common: created directory at: artifacts]
[2024-01-11 15:20:38,322: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:20:38,323: INFO: 456661562: downloading dataset fromhttps://drive.google.com/file/d/<10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:20:38,890: INFO: 456661562: downloaded dataset fromhttps://drive.google.com/file/d/<10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:21:32,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:21:32,670: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:21:32,672: INFO: common: created directory at: artifacts]
[2024-01-11 15:21:32,673: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:21:32,673: INFO: 456661562: downloading dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:21:34,293: INFO: 456661562: downloaded dataset fromhttps://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:23:50,032: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:23:50,034: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:23:50,035: INFO: common: created directory at: artifacts]
[2024-01-11 15:23:50,036: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:23:50,036: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:23:51,480: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/10RqZ8VFZJJtdlUIwDWT5HljsiR-iykwE/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:29:44,702: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-11 15:29:44,709: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-11 15:29:44,709: INFO: common: created directory at: artifacts]
[2024-01-11 15:29:44,710: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-11 15:29:44,711: INFO: 3199809212: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-11 15:29:46,025: INFO: 3199809212: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-23 19:21:00,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 19:21:00,167: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 19:21:00,169: INFO: common: created directory at: artifacts]
[2024-01-23 19:21:00,170: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-23 19:21:00,852: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-23 19:22:29,476: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-23 19:22:29,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 19:22:29,478: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 19:22:29,478: INFO: common: created directory at: artifacts]
[2024-01-23 19:22:29,484: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-23 19:22:29,484: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-23 19:22:31,934: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-23 19:22:32,417: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-23 19:22:32,418: INFO: main: .....stage prepare base model started ....]
[2024-01-23 19:22:32,419: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 19:22:32,420: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 19:22:32,421: INFO: common: created directory at: artifacts]
[2024-01-23 19:22:32,421: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-23 19:22:32,771: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-23 19:22:32,990: INFO: main: ..... stage prepare base model completed .....]
[2024-01-23 20:05:46,917: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 20:05:46,921: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 20:05:46,923: INFO: common: created directory at: artifacts]
[2024-01-23 20:05:46,925: INFO: common: created directory at: artifacts\training]
[2024-01-23 20:08:33,535: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 20:08:33,538: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 20:08:33,539: INFO: common: created directory at: artifacts]
[2024-01-23 20:08:33,541: INFO: common: created directory at: artifacts\training]
[2024-01-23 20:09:41,036: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 20:09:41,039: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 20:09:41,042: INFO: common: created directory at: artifacts]
[2024-01-23 20:09:41,044: INFO: common: created directory at: artifacts\training]
[2024-01-23 20:10:43,003: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 20:10:43,008: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 20:10:43,010: INFO: common: created directory at: artifacts]
[2024-01-23 20:10:43,013: INFO: common: created directory at: artifacts\training]
[2024-01-23 20:54:15,295: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-23 20:54:15,301: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 20:54:15,301: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 20:54:15,307: INFO: common: created directory at: artifacts]
[2024-01-23 20:54:15,307: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-23 20:54:15,307: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-23 20:54:27,798: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-23 20:54:29,081: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-23 20:54:29,081: INFO: main: .....stage prepare base model started ....]
[2024-01-23 20:54:29,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 20:54:29,089: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 20:54:29,089: INFO: common: created directory at: artifacts]
[2024-01-23 20:54:29,089: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-23 20:54:36,383: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-23 20:54:36,999: INFO: main: ..... stage prepare base model completed .....]
[2024-01-23 20:54:36,999: INFO: main: .....stage TRAINING started ....]
[2024-01-23 20:54:37,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 20:54:37,016: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 20:54:37,016: INFO: common: created directory at: artifacts]
[2024-01-23 20:54:37,016: ERROR: main: 'ConfigurationManager' object has no attribute 'get_training_config']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_03_model_training.py", line 13, in main
    training_config = config.get_training_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_training_config'
[2024-01-23 21:09:25,277: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-23 21:09:25,281: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 21:09:25,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 21:09:25,281: INFO: common: created directory at: artifacts]
[2024-01-23 21:09:25,281: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-23 21:09:25,281: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-23 21:09:55,626: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-23 21:09:56,596: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-23 21:09:56,596: INFO: main: .....stage prepare base model started ....]
[2024-01-23 21:09:56,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 21:09:56,596: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 21:09:56,596: INFO: common: created directory at: artifacts]
[2024-01-23 21:09:56,596: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-23 21:10:01,154: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-23 21:10:01,780: INFO: main: ..... stage prepare base model completed .....]
[2024-01-23 21:10:01,785: INFO: main: .....stage TRAINING started ....]
[2024-01-23 21:10:01,790: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 21:10:01,791: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 21:10:01,791: INFO: common: created directory at: artifacts]
[2024-01-23 21:10:01,791: INFO: common: created directory at: artifacts\training]
[2024-01-23 21:10:45,317: INFO: main: ..... stage TRAINING completed .....]
[2024-01-23 21:31:32,265: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 21:31:32,269: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 21:31:32,269: INFO: common: created directory at: artifacts]
[2024-01-23 21:32:00,980: INFO: common: json file is saved scores.json]
[2024-01-23 21:40:57,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 21:40:57,044: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 21:40:57,044: INFO: common: created directory at: artifacts]
[2024-01-23 21:41:24,462: INFO: common: json file is saved scores.json]
[2024-01-23 21:42:33,212: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-23 21:42:33,219: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-23 21:42:33,219: INFO: common: created directory at: artifacts]
[2024-01-23 21:42:59,300: INFO: common: json file is saved scores.json]
[2024-01-24 14:27:48,729: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 14:27:48,746: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 14:27:48,746: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 14:27:48,746: INFO: common: created directory at: artifacts]
[2024-01-24 14:27:48,746: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 14:27:48,746: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 14:27:48,764: ERROR: main: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018F4DFA7520>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
Traceback (most recent call last):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018F4DFA7520>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018F4DFA7520>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 24, in download_file
    raise e
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\gdown\download.py", line 157, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018F4DFA7520>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))
[2024-01-24 17:57:08,710: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 17:57:08,712: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 17:57:08,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 17:57:08,715: INFO: common: created directory at: artifacts]
[2024-01-24 17:57:08,715: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 17:57:08,715: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 17:57:15,657: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 17:57:16,046: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 17:57:16,046: INFO: main: .....stage prepare base model started ....]
[2024-01-24 17:57:16,047: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 17:57:16,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 17:57:16,049: INFO: common: created directory at: artifacts]
[2024-01-24 17:57:16,049: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 17:57:19,191: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 17:57:19,434: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 17:57:19,434: INFO: main: .....stage TRAINING started ....]
[2024-01-24 17:57:19,435: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 17:57:19,438: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 17:57:19,438: INFO: common: created directory at: artifacts]
[2024-01-24 17:57:19,439: INFO: common: created directory at: artifacts\training]
[2024-01-24 17:57:33,047: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 17:59:51,507: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 17:59:51,510: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 17:59:51,512: INFO: common: created directory at: artifacts]
[2024-01-24 18:00:01,289: INFO: common: json file is saved scores.json]
[2024-01-24 18:02:59,799: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 18:02:59,811: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 18:02:59,815: INFO: common: created directory at: artifacts]
[2024-01-24 18:03:08,135: INFO: common: json file saved at: scores.json]
[2024-01-24 18:03:11,492: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 18:03:12,366: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpug578l7x\model\data\model\assets]
[2024-01-24 18:37:55,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 18:37:55,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 18:37:55,878: INFO: common: created directory at: artifacts]
[2024-01-24 18:38:10,102: INFO: common: json file saved at: scores.json]
[2024-01-24 18:38:13,262: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 18:38:13,969: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmp_7jq_tep\model\data\model\assets]
[2024-01-24 19:04:02,333: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 19:04:02,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 19:04:02,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 19:04:02,333: INFO: common: created directory at: artifacts]
[2024-01-24 19:04:02,333: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 19:04:02,333: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 19:04:10,166: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 19:04:10,640: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 19:04:10,640: INFO: main: .....stage prepare base model started ....]
[2024-01-24 19:04:10,655: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 19:04:10,655: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 19:04:10,655: INFO: common: created directory at: artifacts]
[2024-01-24 19:04:10,655: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 19:04:13,539: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 19:04:13,899: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 19:04:13,900: INFO: main: .....stage TRAINING started ....]
[2024-01-24 19:04:13,902: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 19:04:13,904: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 19:04:13,904: INFO: common: created directory at: artifacts]
[2024-01-24 19:04:13,904: INFO: common: created directory at: artifacts\training]
[2024-01-24 19:04:28,585: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 19:04:28,585: INFO: main: .....stage model evaluation started ....]
[2024-01-24 19:04:28,585: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 19:04:28,595: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 19:04:28,595: INFO: common: created directory at: artifacts]
[2024-01-24 19:04:31,391: INFO: common: json file saved at: scores.json]
[2024-01-24 19:04:31,391: INFO: common: json file saved at: scores.json]
[2024-01-24 19:04:32,533: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 19:04:33,226: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmp873xu77o\model\data\model\assets]
[2024-01-24 19:04:45,755: ERROR: main: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 18, in main
    evaluation.log_into_mlflow()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\model_evaluation_mlflow.py", line 71, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}
[2024-01-24 20:12:58,559: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 20:12:58,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:12:58,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:12:58,565: INFO: common: created directory at: artifacts]
[2024-01-24 20:12:58,565: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 20:12:58,565: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 20:13:22,758: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 20:13:23,188: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 20:13:23,188: INFO: main: .....stage prepare base model started ....]
[2024-01-24 20:13:23,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:13:23,194: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:13:23,194: INFO: common: created directory at: artifacts]
[2024-01-24 20:13:23,194: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 20:13:25,720: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 20:13:26,091: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 20:13:26,091: INFO: main: .....stage TRAINING started ....]
[2024-01-24 20:13:26,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:13:26,097: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:13:26,097: INFO: common: created directory at: artifacts]
[2024-01-24 20:13:26,097: INFO: common: created directory at: artifacts\training]
[2024-01-24 20:13:44,237: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 20:13:44,237: INFO: main: .....stage model evaluation started ....]
[2024-01-24 20:13:44,241: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:13:44,243: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:13:44,243: INFO: common: created directory at: artifacts]
[2024-01-24 20:13:47,006: INFO: common: json file saved at: scores.json]
[2024-01-24 20:13:47,006: INFO: common: json file saved at: scores.json]
[2024-01-24 20:13:48,163: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 20:13:48,806: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpnj230juh\model\data\model\assets]
[2024-01-24 20:14:00,724: ERROR: main: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 18, in main
    evaluation.log_into_mlflow()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\model_evaluation_mlflow.py", line 71, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}
[2024-01-24 20:16:15,430: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:16:15,435: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:16:15,437: INFO: common: created directory at: artifacts]
[2024-01-24 20:16:24,224: INFO: common: json file saved at: scores.json]
[2024-01-24 20:16:27,528: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 20:16:28,320: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmp74p_zuer\model\data\model\assets]
[2024-01-24 20:26:30,058: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 20:26:30,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:26:30,069: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:26:30,069: INFO: common: created directory at: artifacts]
[2024-01-24 20:26:30,069: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 20:26:30,069: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 20:26:39,506: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 20:26:39,910: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 20:26:39,910: INFO: main: .....stage prepare base model started ....]
[2024-01-24 20:26:39,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:26:39,925: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:26:39,925: INFO: common: created directory at: artifacts]
[2024-01-24 20:26:39,925: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 20:26:41,990: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 20:26:42,510: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 20:26:42,510: INFO: main: .....stage TRAINING started ....]
[2024-01-24 20:26:42,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:26:42,520: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:26:42,520: INFO: common: created directory at: artifacts]
[2024-01-24 20:26:42,520: INFO: common: created directory at: artifacts\training]
[2024-01-24 20:27:06,396: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 20:27:06,396: INFO: main: .....stage model evaluation started ....]
[2024-01-24 20:27:06,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 20:27:06,408: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 20:27:06,413: INFO: common: created directory at: artifacts]
[2024-01-24 20:27:10,945: INFO: common: json file saved at: scores.json]
[2024-01-24 20:27:13,100: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 20:27:14,645: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpzfk_2xn6\model\data\model\assets]
[2024-01-24 20:27:31,022: ERROR: main: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 17, in main
    evaluation.log_into_mlflow()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\model_evaluation_mlflow.py", line 71, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
[2024-01-24 21:30:38,540: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 21:30:38,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:30:38,540: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:30:38,540: INFO: common: created directory at: artifacts]
[2024-01-24 21:30:38,540: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 21:30:38,540: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:31:43,027: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:31:43,458: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 21:31:43,458: INFO: main: .....stage prepare base model started ....]
[2024-01-24 21:31:43,465: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:31:43,465: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:31:43,465: INFO: common: created directory at: artifacts]
[2024-01-24 21:31:43,465: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 21:31:45,414: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 21:31:45,751: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 21:31:45,751: INFO: main: .....stage TRAINING started ....]
[2024-01-24 21:31:45,751: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:31:45,756: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:31:45,756: INFO: common: created directory at: artifacts]
[2024-01-24 21:31:45,756: INFO: common: created directory at: artifacts\training]
[2024-01-24 21:31:58,718: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 21:31:58,718: INFO: main: .....stage model evaluation started ....]
[2024-01-24 21:31:58,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:31:58,718: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:31:58,718: INFO: common: created directory at: artifacts]
[2024-01-24 21:32:01,493: INFO: common: json file saved at: scores.json]
[2024-01-24 21:32:02,622: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 21:32:03,192: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpt38mmcro\model\data\model\assets]
[2024-01-24 21:32:09,538: ERROR: main: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 17, in main
    evaluation.log_into_mlflow()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\model_evaluation_mlflow.py", line 71, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}
[2024-01-24 21:38:58,415: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:38:58,418: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:38:58,418: INFO: common: created directory at: artifacts]
[2024-01-24 21:39:06,001: INFO: common: json file saved at: scores.json]
[2024-01-24 21:39:08,921: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 21:39:09,347: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpt0irko23\model\data\model\assets]
[2024-01-24 21:41:51,590: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 21:41:51,590: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:41:51,595: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:41:51,595: INFO: common: created directory at: artifacts]
[2024-01-24 21:41:51,595: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 21:41:51,596: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:42:05,867: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:42:06,289: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 21:42:06,289: INFO: main: .....stage prepare base model started ....]
[2024-01-24 21:42:06,289: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:42:06,289: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:42:06,289: INFO: common: created directory at: artifacts]
[2024-01-24 21:42:06,289: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 21:42:08,376: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 21:42:08,746: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 21:42:08,746: INFO: main: .....stage TRAINING started ....]
[2024-01-24 21:42:08,746: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:42:08,746: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:42:08,746: INFO: common: created directory at: artifacts]
[2024-01-24 21:42:08,756: INFO: common: created directory at: artifacts\training]
[2024-01-24 21:42:22,290: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 21:42:22,290: INFO: main: .....stage model evaluation started ....]
[2024-01-24 21:42:22,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:42:22,300: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:42:22,300: INFO: common: created directory at: artifacts]
[2024-01-24 21:42:25,095: INFO: common: json file saved at: scores.json]
[2024-01-24 21:42:25,095: INFO: common: json file saved at: scores.json]
[2024-01-24 21:42:31,714: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 21:42:32,201: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpnu2g24hg\model\data\model\assets]
[2024-01-24 21:43:37,779: INFO: main: ..... stage model evaluation completed .....]
[2024-01-24 21:48:44,947: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 21:48:44,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:48:44,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:48:44,954: INFO: common: created directory at: artifacts]
[2024-01-24 21:48:44,954: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 21:48:44,954: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:48:44,961: ERROR: main: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2B0C60460>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
Traceback (most recent call last):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001E2B0C60460>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2B0C60460>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 24, in download_file
    raise e
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\gdown\download.py", line 157, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2B0C60460>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))
[2024-01-24 21:50:04,855: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 21:50:04,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:50:04,858: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:50:04,858: INFO: common: created directory at: artifacts]
[2024-01-24 21:50:04,858: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 21:50:04,859: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:50:16,212: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:50:16,706: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 21:50:16,706: INFO: main: .....stage prepare base model started ....]
[2024-01-24 21:50:16,706: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:50:16,706: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:50:16,706: INFO: common: created directory at: artifacts]
[2024-01-24 21:50:16,706: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 21:50:19,471: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 21:50:19,886: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 21:50:19,886: INFO: main: .....stage TRAINING started ....]
[2024-01-24 21:50:19,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:50:19,896: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:50:19,896: INFO: common: created directory at: artifacts]
[2024-01-24 21:50:19,896: INFO: common: created directory at: artifacts\training]
[2024-01-24 21:50:35,628: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 21:50:35,628: INFO: main: .....stage model evaluation started ....]
[2024-01-24 21:50:35,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:50:35,628: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:50:35,628: INFO: common: created directory at: artifacts]
[2024-01-24 21:50:38,498: INFO: common: json file saved at: scores.json]
[2024-01-24 21:50:38,498: INFO: common: json file saved at: scores.json]
[2024-01-24 21:50:39,558: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 21:50:40,200: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpegmtn2_a\model\data\model\assets]
[2024-01-24 21:50:46,821: ERROR: main: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
  File "c:\users\rvaib\onedrive\desktop\kidney-disease-dl-classifier\src\cnnClassifier\components\model_evaluation_mlflow.py", line 71, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 416, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 106, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "C:\Users\rvaib\.conda\envs\gpuenv\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
[2024-01-24 21:54:13,018: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 21:54:13,020: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:54:13,021: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:54:13,022: INFO: common: created directory at: artifacts]
[2024-01-24 21:54:13,022: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 21:54:13,022: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:55:18,070: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 21:55:19,018: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 21:55:19,018: INFO: main: .....stage prepare base model started ....]
[2024-01-24 21:55:19,022: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:55:19,024: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:55:19,025: INFO: common: created directory at: artifacts]
[2024-01-24 21:55:19,025: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 21:55:20,829: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 21:55:21,236: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 21:55:21,236: INFO: main: .....stage TRAINING started ....]
[2024-01-24 21:55:21,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:55:21,246: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:55:21,246: INFO: common: created directory at: artifacts]
[2024-01-24 21:55:21,246: INFO: common: created directory at: artifacts\training]
[2024-01-24 21:55:33,211: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 21:55:33,231: INFO: main: .....stage model evaluation started ....]
[2024-01-24 21:55:33,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 21:55:33,231: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 21:55:33,231: INFO: common: created directory at: artifacts]
[2024-01-24 21:55:36,035: INFO: common: json file saved at: scores.json]
[2024-01-24 21:55:36,035: INFO: common: json file saved at: scores.json]
[2024-01-24 21:55:38,684: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 21:55:39,259: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpum_uz9_m\model\data\model\assets]
[2024-01-24 21:56:18,466: INFO: main: ..... stage model evaluation completed .....]
[2024-01-24 22:01:40,623: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 22:01:40,623: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:01:40,623: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:01:40,623: INFO: common: created directory at: artifacts]
[2024-01-24 22:01:40,623: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 22:01:40,623: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 22:02:39,666: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 22:02:40,079: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 22:02:40,094: INFO: main: .....stage prepare base model started ....]
[2024-01-24 22:02:40,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:02:40,094: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:02:40,110: INFO: common: created directory at: artifacts]
[2024-01-24 22:02:40,110: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 22:02:41,705: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 22:02:42,045: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 22:02:42,045: INFO: main: .....stage TRAINING started ....]
[2024-01-24 22:02:42,045: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:02:42,055: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:02:42,055: INFO: common: created directory at: artifacts]
[2024-01-24 22:02:42,055: INFO: common: created directory at: artifacts\training]
[2024-01-24 22:02:53,866: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 22:02:53,866: INFO: main: .....stage model evaluation started ....]
[2024-01-24 22:02:53,866: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:02:53,866: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:02:53,866: INFO: common: created directory at: artifacts]
[2024-01-24 22:02:56,517: INFO: common: json file saved at: scores.json]
[2024-01-24 22:02:56,520: INFO: common: json file saved at: scores.json]
[2024-01-24 22:02:59,357: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 22:03:00,007: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpv7afcbv0\model\data\model\assets]
[2024-01-24 22:03:39,646: INFO: main: ..... stage model evaluation completed .....]
[2024-01-24 22:38:13,209: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 22:38:13,209: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:38:13,209: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:38:13,209: INFO: common: created directory at: artifacts]
[2024-01-24 22:38:13,209: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 22:38:13,209: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 22:40:14,784: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 22:40:15,204: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 22:40:15,204: INFO: main: .....stage prepare base model started ....]
[2024-01-24 22:40:15,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:40:15,220: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:40:15,220: INFO: common: created directory at: artifacts]
[2024-01-24 22:40:15,220: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 22:40:17,117: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 22:40:17,433: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 22:40:17,433: INFO: main: .....stage TRAINING started ....]
[2024-01-24 22:40:17,433: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:40:17,443: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:40:17,443: INFO: common: created directory at: artifacts]
[2024-01-24 22:40:17,443: INFO: common: created directory at: artifacts\training]
[2024-01-24 22:40:29,905: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 22:40:29,905: INFO: main: .....stage model evaluation started ....]
[2024-01-24 22:40:29,906: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 22:40:29,906: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 22:40:29,906: INFO: common: created directory at: artifacts]
[2024-01-24 22:40:32,572: INFO: common: json file saved at: scores.json]
[2024-01-24 22:40:32,572: INFO: common: json file saved at: scores.json]
[2024-01-24 22:40:35,307: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 22:40:35,797: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmp0mm693fc\model\data\model\assets]
[2024-01-24 22:41:13,971: INFO: main: ..... stage model evaluation completed .....]
[2024-01-24 23:08:32,409: INFO: stage_01_data_ingestion: .....stage Data ingestion stage started ....]
[2024-01-24 23:08:32,415: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:08:32,422: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:08:32,426: INFO: common: created directory at: artifacts]
[2024-01-24 23:08:32,433: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 23:08:32,433: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 23:09:13,744: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 23:09:14,145: INFO: stage_01_data_ingestion: ..... stage Data ingestion stage completed .....]
[2024-01-24 23:09:22,994: INFO: stage_02_prepare_base_model: .....stage preapare base model started ....]
[2024-01-24 23:09:22,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:09:22,998: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:09:22,998: INFO: common: created directory at: artifacts]
[2024-01-24 23:09:22,999: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 23:09:24,606: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 23:09:24,958: INFO: stage_02_prepare_base_model: ..... stage preapare base model completed .....]
[2024-01-24 23:09:28,768: INFO: stage_03_model_training: .....stage TRAINING started ....]
[2024-01-24 23:09:28,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:09:28,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:09:28,771: INFO: common: created directory at: artifacts]
[2024-01-24 23:09:28,771: INFO: common: created directory at: artifacts\training]
[2024-01-24 23:09:40,963: INFO: stage_03_model_training: ..... stage TRAINING completed .....]
[2024-01-24 23:09:47,415: INFO: stage_04_model_evaluation: .....stage model evaluation started ....]
[2024-01-24 23:09:47,416: ERROR: stage_04_model_evaluation: main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 29, in <module>
    obj.main()
TypeError: main() missing 1 required positional argument: 'self'
[2024-01-24 23:10:12,719: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-24 23:10:12,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:10:12,722: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:10:12,723: INFO: common: created directory at: artifacts]
[2024-01-24 23:10:12,723: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-24 23:10:12,723: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 23:11:02,483: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-24 23:11:02,914: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-24 23:11:02,914: INFO: main: .....stage prepare base model started ....]
[2024-01-24 23:11:02,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:11:02,918: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:11:02,921: INFO: common: created directory at: artifacts]
[2024-01-24 23:11:02,921: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-24 23:11:04,632: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-24 23:11:05,015: INFO: main: ..... stage prepare base model completed .....]
[2024-01-24 23:11:05,017: INFO: main: .....stage TRAINING started ....]
[2024-01-24 23:11:05,019: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:11:05,021: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:11:05,022: INFO: common: created directory at: artifacts]
[2024-01-24 23:11:05,022: INFO: common: created directory at: artifacts\training]
[2024-01-24 23:11:14,792: INFO: main: ..... stage TRAINING completed .....]
[2024-01-24 23:11:14,796: INFO: main: .....stage model evaluation started ....]
[2024-01-24 23:11:14,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:11:14,799: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:11:14,800: INFO: common: created directory at: artifacts]
[2024-01-24 23:11:17,791: INFO: common: json file saved at: scores.json]
[2024-01-24 23:11:17,792: INFO: common: json file saved at: scores.json]
[2024-01-24 23:11:20,987: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 23:11:21,480: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpj_so4yi_\model\data\model\assets]
[2024-01-24 23:11:59,242: INFO: main: ..... stage model evaluation completed .....]
[2024-01-24 23:13:48,152: INFO: stage_04_model_evaluation: .....stage model evaluation started ....]
[2024-01-24 23:13:48,152: ERROR: stage_04_model_evaluation: main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 29, in <module>
    obj.main()
TypeError: main() missing 1 required positional argument: 'self'
[2024-01-24 23:16:13,985: INFO: stage_04_model_evaluation: .....stage model evaluation started ....]
[2024-01-24 23:16:13,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-24 23:16:13,989: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-24 23:16:13,989: INFO: common: created directory at: artifacts]
[2024-01-24 23:16:21,845: INFO: common: json file saved at: scores.json]
[2024-01-24 23:16:21,846: INFO: common: json file saved at: scores.json]
[2024-01-24 23:16:25,062: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-24 23:16:25,459: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmpoza3znaq\model\data\model\assets]
[2024-01-24 23:17:02,071: INFO: stage_04_model_evaluation: ..... stage model evaluation completed .....]
[2024-01-25 18:22:53,159: INFO: main: .....stage Data ingestion stage started ....]
[2024-01-25 18:22:53,160: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-25 18:22:53,160: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-25 18:22:53,160: INFO: common: created directory at: artifacts]
[2024-01-25 18:22:53,160: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-25 18:22:53,160: INFO: data_ingestion: downloading dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-25 18:23:01,900: INFO: data_ingestion: downloaded dataset fromhttps://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-25 18:23:02,366: INFO: main: ..... stage Data ingestion stage completed .....]
[2024-01-25 18:23:02,366: INFO: main: .....stage prepare base model started ....]
[2024-01-25 18:23:02,372: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-25 18:23:02,372: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-25 18:23:02,372: INFO: common: created directory at: artifacts]
[2024-01-25 18:23:02,372: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-25 18:23:06,717: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-25 18:23:07,105: INFO: main: ..... stage prepare base model completed .....]
[2024-01-25 18:23:07,105: INFO: main: .....stage TRAINING started ....]
[2024-01-25 18:23:07,111: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-25 18:23:07,111: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-25 18:23:07,111: INFO: common: created directory at: artifacts]
[2024-01-25 18:23:07,111: INFO: common: created directory at: artifacts\training]
[2024-01-25 18:23:26,578: INFO: main: ..... stage TRAINING completed .....]
[2024-01-25 18:23:26,578: INFO: main: .....stage model evaluation started ....]
[2024-01-25 18:23:26,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-25 18:23:26,590: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-25 18:23:26,590: INFO: common: created directory at: artifacts]
[2024-01-25 18:23:30,953: INFO: common: json file saved at: scores.json]
[2024-01-25 18:23:30,953: INFO: common: json file saved at: scores.json]
[2024-01-25 18:23:38,079: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2024-01-25 18:23:39,258: INFO: builder_impl: Assets written to: C:\Users\rvaib\AppData\Local\Temp\tmp0onrrz3b\model\data\model\assets]
[2024-01-25 18:24:22,710: INFO: main: ..... stage model evaluation completed .....]
[2024-01-25 19:05:44,292: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.107:8080]
[2024-01-25 19:05:44,308: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-25 19:05:59,364: INFO: _internal: 127.0.0.1 - - [25/Jan/2024 19:05:59] "GET / HTTP/1.1" 200 -]
[2024-01-25 19:07:50,428: INFO: _internal: 127.0.0.1 - - [25/Jan/2024 19:07:50] "[33mPOST /predict HTTP/1.1[0m" 404 -]
[2024-01-25 19:09:24,468: INFO: _internal: 127.0.0.1 - - [25/Jan/2024 19:09:24] "GET / HTTP/1.1" 200 -]
[2024-01-25 19:09:32,555: INFO: _internal: 127.0.0.1 - - [25/Jan/2024 19:09:32] "[33mPOST /predict HTTP/1.1[0m" 404 -]
